export const BEVERAGE_TYPES = [
  "Espresso",
  "Ristretto",
  "Lungo",
  "Americano",
  "Doppio",
  "Cappuccino",
  "Latte",
  "Flat White",
  "Macchiato",
  "Cortado",
  "Mocha",
  "Affogato",
  "Irish Coffee",
  "Café au Lait",
  "Iced Coffee",
  "Cold Brew",
  "Nitro Cold Brew",
  "Frappe",
  "Vienna Coffee",
  "Turkish Coffee",
  "Filter Coffee",
  "Moka Pot",
  "French Press",
  "Aeropress",
  "Other",
];
